version: 2.1

orbs:
  node: circleci/node@5.1.0
  macos: circleci/macos@2.3.4
  react-native: react-native-community/react-native@7.1.1 #ab

jobs: # a basic unit of work in a run
  build:
    macos:
      xcode: 14.2.0 # indicate our selected version of Xcodez
    steps:
      - checkout
      #- macos/preboot-simulator:
      #    version: "16.2"
      #    platform: "iOS"
      #    device: "iPhone 14 Pro"
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: yarn
      - rn/ios_build:
          build_configuration: Release
          device: iPhone 14
          pod_install_directory: ios
          name: build_ios_release
          project_path: ios/ytview.xcodeproj
          scheme: ytview
      #- run:
          #name: flutter build
          #command: flutter build ipa --export-method development
          #command: npx react-native run-ios --mode=Release
          #no_output_timeout: 1m30s
      #- run:
          # build our application
          #name: Build Application
          #command: xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          #working_directory: iostest/ios/Runner.xcodeproj
          #working_directory: calendar
      #- run:
          # compress Xcode's build output so that it can be stored as an artifact
          #name: Compress app for storage
          #command: zip -r app.zip build/Release/circleci-demo-macos.app
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          #command: zip -r app.zip .
          command: ls ios > a.txt
          #when: on_fail
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          #path: app.zip
          path: a.txt
          destination: app

workflows:
  test_build:
    jobs:
      - build